from django.urls import path, include
from rest_framework.routers import DefaultRouter
from tasks.views import TaskViewSet, EditTasks


# Create a router instance
router = DefaultRouter()
# Register the TaskViewSet with the router, using the base URL 'tasks'
router.register(r'tasks', TaskViewSet)
# router.register(r'tasks', edit_tasks)

# Define the URL patterns
urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),
        # path('tasks/', schedule, name='edit'),
    # path('tasks/<int:pk>', EditTasks.edit_tasks, name='edit'),
    path('tasks/<int:pk>', EditTasks.delete_task, name='delete'),
]
