# Generated by Django 4.1.7 on 2023-04-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_completed_task_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='Low', max_length=255),
            preserve_default=False,
        ),
    ]
