# Generated by Django 4.2.5 on 2023-11-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_alter_meeting_meeting_tasks'),
        ('tasks', '0005_task_meeting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='meetings',
            field=models.ManyToManyField(blank=True, to='meeting.meeting'),
        ),
    ]
