# Generated by Django 4.2.5 on 2023-11-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_meeting_id'),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_tasks',
            field=models.ManyToManyField(to='tasks.task'),
        ),
    ]
