# Generated by Django 4.2.5 on 2023-11-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_meeting_meeting_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='agenda',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendees',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
