# Generated by Django 4.2.5 on 2023-11-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_meeting_agenda_alter_meeting_attendees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='duration',
        ),
    ]
