# Generated by Django 4.2.5 on 2023-11-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_meeting_id'),
        ('meeting', '0004_remove_meeting_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_tasks',
            field=models.ManyToManyField(blank=True, to='tasks.task'),
        ),
    ]
