# Generated by Django 4.2.5 on 2023-11-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_deleted'),
        ('meeting', '0005_alter_meeting_meeting_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='attendees',
        ),
        migrations.AddField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='person.person'),
        ),
    ]
