# Generated by Django 4.2.5 on 2023-11-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
